#! /bin/bash

# Takes a directory as argument
usage(){
	echo "Usage: dirwark dir"
	exit 1
}
work(){
	#Push directory into stack
	pushd "$1"
	
	echo "=======================================" 1>&2
	echo "In Directory: $PWD" 1>&2
	while read -r name; do
		#echo $name
		#new_name="$(echo $name | sed 's/.pgp$//' | sed 's/ /_/g')"
		echo $name
		#mv $name $new_name
		#rm "$name"
		#echo $namear
		#echo "New: $new_name" 1>&2
		#gpg -d -o "$new_name" "$name"
		#rm $name
		#gunzip "$new_name"
		#gunzip "$name"
		#tar -xf $name
	done < <(find . -maxdepth 1 -mindepth 1 -type f -print)

	while read -r name; do
		work "$name"
	done < <(find . -maxdepth 1 -mindepth 1 -type d -print)

	# Go back in directory walk
	popd 2>&1 1>/dev/null

	return
	}

if [[ "$#" -lt 1 ]]; then
	usage
fi

if [[ -d "$1" ]]; then
	# Time for work
	cd "$1"
	work "$1" 
else
	echo "The is no such directory."
	exit 1
fi

exit 0
