#! /bin/bash

MUSICDIR="${HOME}/Music"
FAV_LIST="$XDG_CONFIG_HOME/mpd/playlists/Favourites.m3u"
SELECTOR="anyrun --plugins libstdin.so"

#Begin functions
#
showcurrent(){
	notify-send "$(mpc status | head -2)"
}

sortlist(){
	local tempfile
	tempfile="$(mktemp)"
	sort "$FAV_LIST" > "$tempfile"
	cat "$tempfile" > "$FAV_LIST"
	rm "$tempfile"
}

addfavourite(){
    CURRENT="$(mpc -f %file% current)"
	GCURRENT="$(echo $CURRENT | sed -E 's/([?*.+{|()[\^$])/\\\1/g')"
	if grep -E -qx -e "$GCURRENT" "$FAV_LIST"; then
		notify-send "Already Favourite"
		return
	fi
	echo "$CURRENT" | tee -a "$FAV_LIST" > /dev/null
	sortlist
}

rmfavourite(){
    CURRENT="$(mpc -f %file% current)"
	GCURRENT="$(echo $CURRENT | sed -E 's/([?*.+{|()[\^$])/\\\1/g')"
	if ! grep -E -qx -e "$GCURRENT" "$FAV_LIST"; then
		notify-send "Already not a favourite"
		return
	fi
	SCURRENT="$(echo $CURRENT | sed -E 's/([\/?*.+{|()[\^$])/\\\1/g')"
	sed -Ei "/^$SCURRENT\$/d" "$FAV_LIST"
}

loadtrack(){
	CHOICE="$(mpc -f "[%position% ] [[[%artist% - ]%title%]|[%file%]]" playlist | $SELECTOR)"
	if [[ $CHOICE == "" ]]; then
		return
	fi
	POS="$(echo "$CHOICE" | cut -f 1 -d ' ')"
	mpc play "$POS"
}

loadalbum(){
	CHOICE="$(mpc list album | $SELECTOR)"
	if [[ $CHOICE == "" ]]; then
		return
	fi
	mpc clear
	mpc findadd "(album == \"$CHOICE\")"
	mpc play
}

loadartist(){
	CHOICE="$(mpc list artist | $SELECTOR)"
	if [[ $CHOICE == "" ]]; then
		return
	fi
	mpc clear
	mpc findadd "( artist == \"$CHOICE\")"
	mpc play
}

loadplaylist(){
	CHOICE="$(mpc lsplaylists | $SELECTOR)"

	if [[ $CHOICE == "" ]]; then
		return
	fi
	mpc clear
	if [[ $CHOICE == "All" ]]; then
		mpc add /
	else
		mpc load "$CHOICE"
	fi
	mpc play
}

loadfolder(){
    cd $MUSICDIR
    CHOICE="$(find . -mindepth 1 -type d | $SELECTOR | sed -E 's/^\.\///')"
	if [[ $CHOICE == "" ]]; then
		return
	fi
    mpc clear
    mpc add "$CHOICE"
    mpc play
}

loadall(){
	mpc clear
	mpc add /
	mpc play
}

# Main execution point
case "$1" in
	ldlist)       loadplaylist      ;;
	ldartist)     loadartist        ;;
	ldalbum)      loadalbum         ;;
	ldtrack)      loadtrack         ;;
	addfav)       addfavourite      ;;
	rmfav)        rmfavourite       ;;
	show)         showcurrent       ;;
	shuffle)      mpc -q shuffle    ;;
	sort)         sortlist          ;;
    ldfolder)     loadfolder        ;;
	ldall)        loadall           ;;
	*)            exit              ;;
esac
